import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import WalletContextProvider from "@/contexts/WalletContextProvider";
import { OpenWalletProvider } from "@/contexts/OpenWalletContext";
import { UILayout } from "@/components/layout/UiLayout";
import "./globals.css";
import "@solana/wallet-adapter-react-ui/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Swag Critters Quest",
  description: "Generated by OxSome!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WalletContextProvider>
          <OpenWalletProvider>
            <UILayout>{children}</UILayout>
          </OpenWalletProvider>
        </WalletContextProvider>
        <Toaster />
      </body>
    </html>
  );
}
